<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Paul Demers - A Boston Based Purveyor of Fine Designery</title>
    <meta name="description" content="Paul Demers is a web generalist that hand-crafts effectively simple solutions to complex design problems.">
    <meta name="author" content="Paul Demers Jr">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:image" content="http://www.demersdesigns.com/apple-touch-icon-114x114-precomposed.png"/>
    <meta property="og:title" content="Paul Demers - A Boston Based Purveyor of Fine Designery"/>
    <meta property="og:url" content="http://www.demersdesigns.com"/>
    <meta property="og:site_name" content="Paul Demers - A Boston Based Purveyor of Fine Designery"/>


    <link rel="shortcut icon" href="./favicon.ico"/>
    <link rel="stylesheet prefetch" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="./css/style.min.css">
    <script src="./js/vendor/modernizr-2.7.1.min.js"></script>
    <script>
  	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  	  ga('create', 'UA-4076744-14', 'demersdesigns.com');
  	  ga('send', 'pageview');
  	</script>
    <script>(function(){var hb = document.createElement('script'); hb.type = 'text/javascript'; hb.async = true; hb.src = "//cdn.hublo.co/5357d0655b62d6811300005e.js"; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(hb, s);})();
    </script>
  </head>
<body>
