<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Paul Demers - A Boston Based Purveyor of Fine Designery</title>
    <meta name="description" content="Paul Demers is a web generalist that hand-crafts effectively simple solutions to complex design problems.">
    <meta name="author" content="Paul Demers Jr">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="http://www.demersdesigns.com/apple-touch-icon-114x114-precomposed.png"/>
    <meta property="og:title" content="Paul Demers - A Boston Based Purveyor of Fine Designery"/>
    <meta property="og:url" content="http://www.demersdesigns.com"/>
    <meta property="og:site_name" content="Paul Demers - A Boston Based Purveyor of Fine Designery"/>
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="icon" sizes="16x16 32x32" href="/favicon.ico">
    <link prefetch rel="stylesheet" href='https://fonts.googleapis.com/css?family=Open+Sans:800|Vollkorn' rel='stylesheet' type='text/css'>
    <!-- build:css css/style.css -->
    <link rel="stylesheet" href="/css/style.css">
    <!-- endbuild -->
  </head>
<body>
