<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Paul Demers - A Boston Based Purveyor of Fine Designery</title>
  <meta name="description" content="Paul Demers is a web generalist that hand-crafts effectively simple solutions to complex design problems.">
  <meta name="author" content="Paul Demers Jr">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:image" content="http://www.demersdesigns.com/apple-touch-icon-114x114-precomposed.png"/>
  <meta property="og:title" content="Paul Demers - A Boston Based Purveyor of Fine Designery"/>
  <meta property="og:url" content="http://www.demersdesigns.com"/>
  <meta property="og:site_name" content="Paul Demers - A Boston Based Purveyor of Fine Designery"/>


  <link rel="shortcut icon" href="./favicon.ico"/>
  <link rel="stylesheet prefetch" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" href="./css/style.min.css">
  <script src="./js/vendor/modernizr-2.7.1.min.js"></script>
</head>
<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->